# Jekyll configuration for GitHub Pages
title: "Elevar Amplifier"
description: "Static API endpoints for footwear catalogs - sneakers and flip flops"
url: "https://tanaygshah.github.io" # Your GitHub Pages domain
baseurl: "" # Empty for root deployment

# GitHub Pages settings
plugins: []

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .github/

# Include files that start with underscores and static files
include:
  - _headers
  - "*.json"
  - "*.txt"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Collections and defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Custom headers for better API responses
headers:
  "/*.json":
    - "Content-Type: application/json; charset=utf-8"
    - "Access-Control-Allow-Origin: *"
  "/*.txt":
    - "Content-Type: text/plain; charset=utf-8"
